--- 
- 
  name: "Install Apache"
  yum: 
    name: httpd
    state: present
- 
  name: "Enable apache on reboot and start"
  service: 
    enabled: true
    name: httpd
    state: started
- 
  copy: 
    dest: /var/www/html/index.html
    src: index.html
  name: "Deploy the project on apache"
  notify: 
    - "Restart apache"
