-
  name: Deploy a web application
  hosts: target1
  tasks:
    - name: create deployment
      shell: 'kubectl create -f webapp-deploy.yaml'

    - name: Create service
      shell: 'kubectl create -f service-demo.yaml'
